language: rust
sudo: false

# run builds for all the trains (and more)
rust:
  - 1.26.0
  - stable
  - beta
  - nightly

# the main build
script:
  - |
      cargo build -v &&
      cargo test -v &&
      cargo doc -v
