[package]
name = "asprim"
version = "0.1.0"
authors = ["bluss"]

description = "Cast any primitive numeric type to any other using `as` with the AsPrim trait."

keywords = ["cast", "numerics", "no_std"]

[dependencies]
